name: ewarrenty
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.5+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # don't forget the ios application Id
  font_awesome_flutter: ^9.1.0
  flutter_swiper: ^1.1.6
  flutter_typeahead: ^3.2.0
  google_fonts: ^2.1.0
  provider: ^5.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.1
  #add ios functions
#  camera: ^0.5.8+17
  modal_progress_hud: ^0.1.3
  shared_preferences: ^2.0.6
  #add ios functions
  image_picker: ^0.8.1+4
#  smooth_page_indicator: ^0.2.0
#  flutter_svg: ^0.19.1
#  splashscreen: ^1.3.5
  pdf: ^3.4.2
  path_provider: ^2.0.2
  flutter_full_pdf_viewer: ^1.0.6
  share: ^2.0.4
  country_code_picker: ^2.0.2
  chopper: ^4.0.1
  cached_network_image: ^3.0.0
  rxdart:
  flutter_image_compress: ^1.0.0
#  flutter_progress_hud: ^1.0.3
#  flutter_launcher_icons: "^0.9.0"
  email_validator: '^2.0.1'
#  flutter_native_splash: ^1.1.8+4
  # Check that you have this dependency (added in the previous step)
  firebase_core: ^1.3.0
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^8.1.2
  flutter_html: ^2.1.0
#  flutter_keyboard_visibility: ^4.0.4
#  http: ^0.12.2
#  modal_bottom_sheet: ^1.0.0
  auto_size_text: ^2.1.0
  firebase_messaging: ^10.0.3
  firebase_crashlytics: ^2.0.0
  upgrader: ^3.2.1


  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter



flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/appicons/icon.png"
  image_path_ios: "assets/images/appicons/icon.png"



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^4.0.0-nullsafety.1
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
#  fonts:
#    - family:  WarrantyIcons
#      fonts:
#        - asset: assets/fonts/WarrantyIcons.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/serialNumber/
   - assets/images/
   - assets/images/PDF/
   - assets/lang/
   - fonts/
   - fonts/alja/
   - fonts/Almarai/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: WarrantyIcons
      fonts:
        - asset: fonts/WarrantyIcons.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
