/// Flutter icons WarrantyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  WarrantyIcons
///      fonts:
///       - asset: fonts/WarrantyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class WarrantyIcons {
  WarrantyIcons._();

  static const _kFontFam = 'WarrantyIcons';
  static const _kFontPkg = null;

  static const IconData warrenty_recycle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_refresh = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_reload = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_send = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_setting = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_shield = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_star = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_stocks = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_target = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_timer = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_web = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_add = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_clear = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_comment = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_correct = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_delete = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_dollar = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_download = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_edit = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_heart = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_image = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_like = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_location = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_lock = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_pdf = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_percent = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_piechart = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData warrenty_plank = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
